### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by ducdetronquito** [python-excel/xlutils#9]
Hi :)

I just figured out that `xlutils` is not Python 3.6 compatible, even if `xlrd` and `xlwt` are.
Is there something blocking you to release `xlutils` for Python 3.6 ?

Have a nice day :)

**Comment by cjw296** [comment]
Do you have evidence that xlutils doesn't work on 3.6 or are you concerned because it does not have it listed in its supported versions?

**Comment by ducdetronquito** [comment]
Hi @cjw296,

My bad, it seems that `xlutils` does have compatibility with Python 3.6: I was just concerned that the compatibility is not mentioned on PyPI and Github.
